# Generated by Django 4.2.14 on 2024-07-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_tariff', models.FloatField()),
                ('area_tariff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readings', models.JSONField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(auto_now_add=True)),
                ('water_billing', models.FloatField()),
                ('area_billing', models.FloatField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.home'),
        ),
    ]
